import { expect, test } from '@playwright/test';

test('Space toggles playback from editor controls without repeating or interrupting typing', async ({ page }) => {
  await page.goto('/#editor');
  await expect(page.getByRole('region', { name: 'Scene editor', exact: true })).toHaveAttribute('aria-busy', 'false');
  await page.getByRole('button', { name: 'Animate', exact: true }).click();
  await page.keyboard.down('Space');
  await expect(page.getByRole('button', { name: 'Pause timeline', exact: true })).toBeVisible();
  await page.keyboard.down('Space');
  await page.keyboard.up('Space');
  await expect.poll(async () => Number((await page.getByLabel('Current time').innerText()).split(' / ')[0])).toBeGreaterThan(.2);
  await page.keyboard.press('Space');
  await expect(page.getByRole('button', { name: 'Play timeline', exact: true })).toBeVisible();

  for (const control of [page.getByRole('button', { name: 'Play timeline', exact: true }), page.getByLabel('Timeline playhead')]) {
    await control.focus();
    await page.keyboard.press('Space');
    await expect(page.getByRole('button', { name: 'Pause timeline', exact: true })).toBeVisible();
    await page.keyboard.press('Space');
    await expect(page.getByRole('button', { name: 'Play timeline', exact: true })).toBeVisible();
  }
  await page.getByRole('button', { name: 'Minimize timeline' }).click();
  await page.keyboard.press('Space');
  await expect(page.getByRole('button', { name: 'Pause timeline', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Expand timeline' })).toBeVisible();
  await page.keyboard.press('Space');

  await page.getByRole('button', { name: 'Scene menu', exact: true }).click();
  await page.getByRole('button', { name: 'Rename project' }).click();
  const name = page.getByRole('textbox', { name: 'Project name' });
  await name.fill('Space'); await name.press('End'); await page.keyboard.press('Space');
  await expect(name).toHaveValue('Space ');
  await expect(page.getByRole('button', { name: 'Pause timeline', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.getByRole('button', { name: 'Output', exact: true }).click();
  await page.keyboard.press('Space');
  expect(await page.evaluate(async () => { const path = '/src/core/store.ts'; return (await import(path)).studio.get().playing; })).toBe(false);
});

test('Space plays and pauses while animation blocks and keyframes have focus', async ({ page }) => {
  await page.goto('/#editor');
  await expect(page.getByRole('region', { name: 'Scene editor', exact: true })).toHaveAttribute('aria-busy', 'false');
  await page.getByRole('button', { name: 'Animations', exact: true }).click();
  await page.getByRole('button', { name: 'Add Drop to floor', exact: true }).click();
  await page.getByRole('button', { name: 'Close animations panel', exact: true }).click();
  const block = page.getByRole('button', { name: 'Drop to floor animation block', exact: true });
  await block.focus();
  await page.keyboard.press('Space');
  await expect(page.getByRole('button', { name: 'Pause timeline', exact: true })).toBeVisible();
  await page.keyboard.press('Space');
  await expect(page.getByRole('button', { name: 'Play timeline', exact: true })).toBeVisible();
  await block.press('Enter');
  await page.locator('.keyframe').first().focus();
  await page.keyboard.press('Space');
  await expect(page.getByRole('button', { name: 'Pause timeline', exact: true })).toBeVisible();
  await page.keyboard.press('Space');
  await expect(page.getByRole('button', { name: 'Play timeline', exact: true })).toBeVisible();
});

for (const viewport of [{ width: 1440, height: 1000 }, { width: 390, height: 844 }]) {
  test(`timeline overlay resizes and minimizes without resizing the scene at ${viewport.width}px`, async ({ page }) => {
    await page.setViewportSize(viewport);
    await page.goto('/#editor');
    await expect(page.getByRole('region', { name: 'Scene editor', exact: true })).toHaveAttribute('aria-busy', 'false');
    await page.getByRole('button', { name: 'Animations', exact: true }).click();
    await page.getByRole('button', { name: 'Add Drop to floor', exact: true }).click();
    await page.getByRole('button', { name: 'Close animations panel', exact: true }).click();
    await page.locator('.camera-switch').getByRole('button', { name: 'Camera view', exact: true }).click();
    await page.getByRole('button', { name: 'Drop to floor animation block', exact: true }).dblclick();
    const project = await page.evaluate(async () => { const path = '/src/core/store.ts'; return (await import(path)).studio.get().project; });
    const keys = page.getByRole('region', { name: 'Drop to floor keyframes', exact: true });
    const divider = page.getByRole('separator', { name: 'Resize timeline' });
    const scene = page.getByRole('region', { name: 'Scene editor', exact: true });
    const initialScene = (await scene.boundingBox())!;
    const frame = page.getByLabel('Camera frame', { exact: true });
    const initialFrame = (await frame.boundingBox())!;
    const handle = (await divider.boundingBox())!;
    await page.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2);
    await page.mouse.down(); await page.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2 + 60, { steps: 6 }); await page.mouse.up();
    await expect(divider).toHaveAttribute('aria-valuenow', '180');
    expect(await scene.boundingBox()).toEqual(initialScene);
    expect(await frame.boundingBox()).toEqual(initialFrame);
    await divider.press('ArrowUp');
    await expect(divider).toHaveAttribute('aria-valuenow', '200');
    await page.getByRole('button', { name: 'Minimize timeline' }).click();
    await expect(keys).toBeHidden();
    expect(await scene.boundingBox()).toEqual(initialScene);
    expect(await frame.boundingBox()).toEqual(initialFrame);
    await page.getByRole('button', { name: 'Play timeline', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Pause timeline', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Pause timeline', exact: true }).click();
    await page.getByRole('button', { name: 'Expand timeline' }).click();
    await expect(keys).toBeVisible();
    await expect(divider).toHaveAttribute('aria-valuenow', '200');
    await divider.press('End');
    await expect(divider).toHaveAttribute('aria-valuenow', String(viewport.height / 2));
    expect(await scene.boundingBox()).toEqual(initialScene);
    expect(await frame.boundingBox()).toEqual(initialFrame);
    await page.setViewportSize({ width: viewport.width, height: 600 });
    await expect(divider).toHaveAttribute('aria-valuenow', '300');
    expect((await scene.boundingBox())!.height).toBeGreaterThanOrEqual(290);
    expect(await page.evaluate(async () => { const path = '/src/core/store.ts'; return (await import(path)).studio.get().project; })).toEqual(project);
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(viewport.width);
  });
}

test('idle keys can be edited, retimed, undone, cleared, and restored', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/#editor');
  await expect(page).toHaveTitle('composition');
  await expect(page.getByRole('region', { name: 'Model animation timeline' })).toHaveCount(0);
  await expect(page.getByRole('complementary', { name: 'Pose controls' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Demo mode' })).toHaveCount(0);
  await expect(page.getByRole('textbox', { name: 'Project name' })).toHaveCount(0);
  expect(await page.locator('.brand').evaluate(el => getComputedStyle(el).backgroundColor)).toBe('rgba(0, 0, 0, 0)');
  await expect(page.locator('canvas')).toBeVisible();
  await expect(page.getByRole('region', { name: 'Scene editor', exact: true })).toHaveAttribute('aria-busy', 'false');
  await expect(page.getByRole('alert')).toHaveCount(0);
  const header = await page.getByRole('banner').boundingBox();
  const viewport = await page.getByRole('region', { name: 'Scene editor', exact: true }).boundingBox();
  expect(viewport!.y).toBeLessThan(header!.y);
  expect(header!.y + header!.height).toBeLessThan(viewport!.y + viewport!.height);
  await page.getByRole('button', { name: 'Scene menu', exact: true }).click();
  await expect(page.getByRole('switch', { name: 'Demo mode' })).not.toBeChecked();
  await page.getByRole('switch', { name: 'Demo mode' }).click();
  await expect(page.getByRole('switch', { name: 'Demo mode' })).toBeChecked();
  await page.getByRole('switch', { name: 'Demo mode' }).click();
  await expect(page.getByRole('switch', { name: 'Demo mode' })).not.toBeChecked();
  await expect(page.getByRole('button', { name: /Chest key at/ })).toHaveCount(5);
  await page.getByRole('switch', { name: 'Demo mode' }).click();
  await page.getByRole('button', { name: 'Scene menu', exact: true }).click();
  await expect(page.locator('.status-message')).toContainText('Demo idle loaded');
  await expect(page.getByRole('button', { name: /Chest key at/ })).toHaveCount(5);
  await page.getByRole('region', { name: 'Scene editor', exact: true }).getByRole('button', { name: 'Chest', exact: true }).click();
  await page.getByLabel('Selected joint', { exact: true }).selectOption('chest');
  const rotationX = page.getByRole('spinbutton', { name: 'rotation X', exact: true });
  await rotationX.fill('25'); await rotationX.press('Enter');
  await expect(rotationX).toHaveValue('25.00');
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(rotationX).toHaveValue('0.00');
  await page.getByRole('button', { name: 'Animate', exact: true }).click();
  await page.getByRole('button', { name: 'Play timeline' }).click();
  await expect.poll(async () => Number((await page.getByLabel('Current time').innerText()).split(' / ')[0])).toBeGreaterThan(.2);
  await page.getByRole('button', { name: 'Pause timeline' }).click();
  const key = page.getByRole('button', { name: 'Chest key at 2.50 seconds', exact: true });
  await key.focus(); await key.press('ArrowRight');
  await expect(page.getByRole('button', { name: 'Chest key at 2.53 seconds', exact: true })).toHaveCount(1);
  await page.getByRole('button', { name: 'Scene menu', exact: true }).click();
  await page.getByRole('button', { name: 'Clear motion', exact: true }).click();
  await page.getByRole('button', { name: 'Clear all motion', exact: true }).click();
  await expect(page.locator('.status-message')).toContainText('static rest pose');
  await expect(page.getByRole('button', { name: /Chest key at/ })).toHaveCount(0);
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(page.getByRole('button', { name: /Chest key at/ })).toHaveCount(5);
  await page.waitForTimeout(450);
  await page.reload();
  await page.getByRole('button', { name: 'Mannequin', exact: true }).click();
  await page.getByLabel('Selected joint', { exact: true }).selectOption('chest');
  await page.getByRole('button', { name: 'Animate', exact: true }).click();
  await expect(page.getByRole('button', { name: /Chest key at/ })).toHaveCount(5);
  await page.screenshot({ path: 'test-results/editor-desktop.png', fullPage: true });
  expect(errors).toEqual([]);
});

test('mobile layout fits and the timeline stays usable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/#editor');
  await expect(page.getByText('composition', { exact: true })).toBeVisible();
  const mobileHeader = await page.getByRole('banner').boundingBox();
  const mobileViewport = await page.getByRole('region', { name: 'Scene editor', exact: true }).boundingBox();
  expect(mobileViewport!.y).toBeLessThan(mobileHeader!.y);
  await expect(page.getByRole('region', { name: 'Scene editor', exact: true })).toHaveAttribute('aria-busy', 'false');
  await expect(page.getByRole('alert')).toHaveCount(0);
  await expect(page.getByText('Pose it. Key it.')).toHaveCount(0);
  await expect(page.getByText('Your movement.')).toHaveCount(0);
  await expect(page.getByText('Keys on this track')).toHaveCount(0);
  await expect(page.locator('.library, .motion-note, .next-step, .statusbar')).toHaveCount(0);
  await expect(page.getByRole('region', { name: 'Model animation timeline' })).toHaveCount(0);
  await page.screenshot({ path: 'test-results/composition-scene-mobile.png', fullPage: true });
  await expect(page.getByRole('button', { name: 'Pose', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Mannequin', exact: true }).click();
  await page.getByLabel('Selected joint', { exact: true }).selectOption('head');
  await expect(page.getByRole('spinbutton', { name: 'rotation X', exact: true })).toBeVisible();
  const pose = await page.getByRole('complementary', { name: 'Pose controls' }).boundingBox();
  expect(pose!.y + pose!.height).toBeLessThanOrEqual(mobileViewport!.y + mobileViewport!.height - 12);
  const selectedViewport = await page.getByRole('region', { name: 'Scene editor', exact: true }).boundingBox();
  expect(selectedViewport!.width).toBe(mobileViewport!.width);
  expect(selectedViewport!.height).toBe(mobileViewport!.height);
  await page.screenshot({ path: 'test-results/composition-pose-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Scene menu', exact: true }).click();
  await page.getByRole('switch', { name: 'Demo mode' }).click();
  await page.getByRole('button', { name: 'Scene menu', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Model animation timeline' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(await page.evaluate(() => document.documentElement.scrollHeight <= window.innerHeight)).toBe(true);
  await expect(page.getByRole('complementary', { name: 'Pose controls' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Scene menu', exact: true }).click();
  await page.getByRole('button', { name: 'Remove character', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Add sample mannequin', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await page.getByRole('button', { name: 'Animate', exact: true }).click();
  if (await page.getByRole('button', { name: 'Dismiss notification' }).count()) await page.getByRole('button', { name: 'Dismiss notification' }).click();
  await page.screenshot({ path: 'test-results/editor-mobile.png', fullPage: true });
});

test('missing character asset reports a load error without crashing the editor', async ({ page }) => {
  await page.route('**/models/humanoid.glb', route => route.abort());
  await page.goto('/#editor');
  await expect(page.getByRole('alert')).toContainText('The humanoid could not load');
  await expect(page.getByRole('button', { name: 'Scene menu', exact: true })).toBeEnabled();
});

test('selected body parts render without shader errors', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (/Shader Error|VALIDATE_STATUS|GL_INVALID|WebGLProgram: Shader/.test(message.text())) errors.push(message.text()); });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/#editor');
  await expect(page.getByRole('region', { name: 'Scene editor', exact: true })).toHaveAttribute('aria-busy', 'false');
  await page.getByRole('button', { name: 'Mannequin', exact: true }).click();
  await page.getByLabel('Selected joint', { exact: true }).selectOption('head');
  await expect(page.getByRole('button', { name: 'Head', exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/selected-head.png', fullPage: true });
  await page.getByLabel('Selected joint', { exact: true }).selectOption('arm.L');
  await page.screenshot({ path: 'test-results/selected-arm.png', fullPage: true });
  await page.getByLabel('Selected joint', { exact: true }).selectOption('model');
  await expect(page.getByRole('button', { name: 'Mannequin', exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});

test('clicking a body part opens floating controls without resizing the scene', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/#editor');
  const scene = page.getByRole('region', { name: 'Scene editor', exact: true });
  await expect(scene).toHaveAttribute('aria-busy', 'false');
  const before = (await scene.boundingBox())!;
  await page.locator('canvas').click({ position: { x: before.width / 2, y: before.height / 2 } });
  await expect(page.getByRole('complementary', { name: 'Pose controls' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Move model', exact: true })).toBeVisible();
  const after = (await scene.boundingBox())!;
  expect(after.width).toBe(before.width);
  expect(after.height).toBe(before.height);
  expect(after.width).toBe(page.viewportSize()!.width);
  await page.getByLabel('Selected joint', { exact: true }).selectOption('head');
  await page.screenshot({ path: 'test-results/floating-pose-controls.png', fullPage: true });
  await page.locator('canvas').click({ position: { x: 80, y: before.height * .7 } });
  await expect(page.getByRole('complementary', { name: 'Pose controls' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Move model', exact: true })).toHaveCount(0);
});
